<?php

/**
 * Created by Xiao.
 * Date: 2018/2/20
 * email: via_chen@126.com
 */

namespace app\controller;

use think\cache\driver\Redis;

class User extends BasicController
{
    /**
     * @var \app\Model\User
     */
    private $_model;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_model = model('User');
    }

    //登录页面
    public function login()
    {
        $request = $this->request->param();
        $this->assign('initStatus',json_encode($request));
        return view('login');
    }

    //正常的用户名+密码方式登录  通过ajax请求登录的
    public function ajax_login()
    {
        if($this->request->isAjax()){
            $data = $this->request->param();
            if(empty($data) || !isset($data['username']) || !isset($data['password'])){
                return json_encode(['status'=>-1,'msg'=>'请确认输入登录用户和登录密码!']);
            }
            $res = $this->_model->login($data);
            return json_encode($res,true);
        }
        return json_encode(['status'=>-1,'msg'=>'请求失败!'],true);
    }

    public function ss()
    {
        $key = cookie('user_key');
        dump($key);
        dump(cache($key['key']));dump(2);
    }

    //注销
    public function logout()
    {
        $key = cookie('user_key');
        dump($key);
        dump(cache($key['key']));
        //清除redis 清除cookie
        cookie('user_key',null);
        cache($key['key'],null);
        $key = cookie('user_key');
        dump($key);
        dump(cache($key['key']));
    }
}